[general]
import = ["~/.config/alacritty/theme.toml"]

[env]
TERM = "xterm-256color"
WINIT_X11_SCALE_FACTOR = "1.0"

[font.normal]
# family = "BlexMono Nerd Font Propo SemiBold"
family = "Berkeley Mono"

[font]
size = 13

[font.glyph_offset]
x = 0
y = 1

[font.offset]
x = 0
y = 1

# [colors.primary]
# background = "#151518"

[window]
decorations = "none"
opacity = 1.0

[window.padding]
x = 0
y = 0
