[env]
TERM = "xterm-256color"
WINIT_X11_SCALE_FACTOR = "1.0"

[font.normal]
family = "BlexMono Nerd Font Propo SemiBold"

[font]
size = 14

[font.glyph_offset]
x = 0
y = 0

[font.offset]
x = 0
y = 0

[colors.primary]
background = "#151518"

[window]
decorations = "none"
opacity = 0.92

[window.padding]
x = 0
y = 2
